export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";
export const ENABLE_TWO_STEP_VERIFICATION_REQUEST = "ENABLE_TWO_STEP_VERIFICATION_REQUEST";
export const ENABLE_TWO_STEP_VERIFICATION_SUCCESS = "ENABLE_TWO_STEP_VERIFICATION_SUCCESS";
export const ENABLE_TWO_STEP_VERIFICATION_FAILURE = "ENABLE_TWO_STEP_VERIFICATION_FAILURE";
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
export const UPLOAD_PROFILE_IMAGE_REQUEST = 'UPLOAD_PROFILE_IMAGE_REQUEST';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAILURE = 'UPLOAD_PROFILE_IMAGE_FAILURE';
export const LOGOUT = "LOGOUT";

export const SEND_RESET_PASSWORD_OTP_REQUEST = "SEND_RESET_PASSWORD_OTP_REQUEST";
export const SEND_RESET_PASSWORD_OTP_SUCCESS = "SEND_RESET_PASSWORD_OTP_SUCCESS";
export const SEND_RESET_PASSWORD_OTP_FAILURE = "SEND_RESET_PASSWORD_OTP_FAILURE";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILURE = "SEND_VERIFICATION_OTP_FAILURE";

export const LOGIN_WITH_OTP_REQUEST = "LOGIN_WITH_OTP_REQUEST";
export const LOGIN_WITH_OTP_SUCCESS = "LOGIN_WITH_OTP_SUCCESS";
export const LOGIN_WITH_OTP_FAILURE = "LOGIN_WITH_OTP_FAILURE";

export const VERIFY_RESET_PASSWORD_OTP_REQUEST = "VERIFY_RESET_PASSWORD_OTP_REQUEST";
export const VERIFY_RESET_PASSWORD_OTP_SUCCESS = "VERIFY_RESET_PASSWORD_OTP_SUCCESS";
export const VERIFY_RESET_PASSWORD_OTP_FAILURE = "VERIFY_RESET_PASSWORD_OTP_FAILURE";
