
export const FETCH_COIN_LIST_REQUEST = "FETCH_COIN_LIST_REQUEST";
export const FETCH_COIN_LIST_SUCCESS = "FETCH_COIN_LIST_SUCCESS";
export const FETCH_COIN_LIST_ERROR = "FETCH_COIN_LIST_ERROR";


export const GET_TOP_50_REQUEST = "GET_TOP_50_REQUEST";
export const GET_TOP_50_SUCCESS = "GET_TOP_50_SUCCESS";
export const GET_TOP_50_ERROR = "GET_TOP_50_ERROR";


export const FETCH_COIN_DETAILS_REQUEST = "FETCH_COIN_DETAILS_REQUEST";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_ERROR = "FETCH_COIN_DETAILS_ERROR";


export const FETCH_COIN_BY_ID_REQUEST = "FETCH_COIN_DETAILS_REQUEST";
export const FETCH_COIN_BY_ID_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_BY_ID_FAILURE = "FETCH_COIN_DETAILS_ERROR";

export const SEARCH_COIN_REQUEST = "SEARCH_COIN_REQUEST";
export const SEARCH_COIN_SUCCESS = "SEARCH_COIN_SUCCESS";
export const SEARCH_COIN_FAILURE = "SEARCH_COIN_FAILURE";

export const FETCH_TRADING_COIN_REQUEST = "FETCH_TRADING_COIN_REQUEST";
export const FETCH_TRADING_COIN_SUCCESS = "FETCH_TRADING_COIN_SUCCESS";
export const FETCH_TRADING_COIN_ERROR = "FETCH_TRADING_COIN_ERROR";