export const CHAT_BOT_REQUEST = "CHAT_BOT_REQUEST";
export const CHAT_BOT_SUCCESS = "CHAT_BOT_SUCCESS";
export const CHAT_BOT_FAILURE = "CHAT_BOT_FAILURE";
export const APPEND_CHAT_MESSAGE = "APPEND_CHAT_MESSAGE";
export const CHAT_ADD_MESSAGE = "CHAT_ADD_MESSAGE";